---
- hosts: idrac 
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - set_boot_order:
        idrac: "{{COMPUTE_IDRAC}}"
        username: "{{IDRAC_USER}}"
        password: "{{IDRAC_PASSWORD}}"
        boot_devices:
          - Index: 0
            Enabled: true
            Id: "BIOS.Setup.1-1#BootSeq#NIC.Integrated.1-4-1#3e179b406f323a545f3b73eed2db6c11" 
            Name: "NIC.Integrated.1-4-1" 
          - Index: 1
            Enabled: true
            Id: "BIOS.Setup.1-1#BootSeq#NIC.Integrated.1-3-1#5cc9f0d5c9574028a10cd1cd3844ee9b"
            Name: "NIC.Integrated.1-3-1"
          - Index: 2 
            Enabled: true 
            Id: "BIOS.Setup.1-1#BootSeq#HardDisk.List.1-1#c9203080df84781e2ca3d512883dee6f" 
            Name: "HardDisk.List.1-1"
      when: COMPUTE_IDRAC != "NA" 
    - set_bios_attr:
        idrac: "{{COMPUTE_IDRAC}}"
        username: "{{IDRAC_USER}}"
        password: "{{IDRAC_PASSWORD}}"
        key_value_pairs:
          LogicalProc: "{{Enabled if ENABLE_HT|bool else Disabled}}" 
          ProcVirtualization: Enabled
          SriovGlobalEnable: Enabled
      register: bios_setting
      when: COMPUTE_IDRAC != "NA" 
    - set_power_state:
        idrac: "{{COMPUTE_IDRAC}}"
        username: "{{IDRAC_USER}}"
        password: "{{IDRAC_PASSWORD}}"
        state: GracefulRestart
      when: bios_setting is defined and bios_setting.changed
    - set_boot_order:
        idrac: "{{CONTROLLER_IDRAC}}"
        username: "{{IDRAC_USER}}"
        password: "{{IDRAC_PASSWORD}}"
        boot_devices:
          - Index: 0
            Enabled: true
            Id: "BIOS.Setup.1-1#BootSeq#NIC.Integrated.1-4-1#3e179b406f323a545f3b73eed2db6c11"
            Name: "NIC.Integrated.1-4-1"
          - Index: 1
            Enabled: true
            Id: "BIOS.Setup.1-1#BootSeq#NIC.Integrated.1-3-1#5cc9f0d5c9574028a10cd1cd3844ee9b"
            Name: "NIC.Integrated.1-3-1"
          - Index: 2
            Enabled: true
            Id: "BIOS.Setup.1-1#BootSeq#HardDisk.List.1-1#c9203080df84781e2ca3d512883dee6f"
            Name: "HardDisk.List.1-1"
      when: CONTROLLER_IDRAC != "NA" 

