---
- hosts: undercloud
  gather_facts: false
  remote_user: root
  tasks:
  - name: install ssh for stack 
    authorized_key:
      user: stack 
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- hosts: undercloud 
  gather_facts: false
  vars_files:
    - vars.yaml
  vars:
    ansible_user: stack
  tasks:
    - name: Create target directory
      file: path=/home/stack/templates-ci/{{TEST_ITEM}}/nic-configs/ state=directory mode=0755

    - name: copy overcloud deployment templates
      template:
        src: "templates/{{TEST_ITEM}}/{{item.src}}"
        dest: "/home/stack/templates-ci/{{TEST_ITEM}}/{{item.dest}}"
        owner: stack
        group: stack
      with_items:
        - src: nic-configs/compute.yaml.j2
          dest: nic-configs/compute.yaml
        - src: nic-configs/controller.yaml.j2
          dest: nic-configs/controller.yaml
        - src: environment.yaml.j2
          dest: environment.yaml
        - src: deploy.sh.j2
          dest: deploy.sh
        - src: disable-telemetry.yaml
          dest: disable-telemetry.yaml
        - src: post-install.yaml
          dest: post-install.yaml
      when: TESTBED is not defined

    - name: copy "{{TESTBED}}" specific deployment templates
      template:
        src: "templates/{{TEST_ITEM}}-{{TESTBED}}/{{item.src}}"
        dest: "/home/stack/templates-ci/{{TEST_ITEM}}/{{item.dest}}"
        owner: stack
        group: stack
      with_items:
        - src: nic-configs/compute.yaml.j2
          dest: nic-configs/compute.yaml
        - src: nic-configs/controller.yaml.j2
          dest: nic-configs/controller.yaml
        - src: environment.yaml.j2
          dest: environment.yaml
        - src: deploy.sh.j2
          dest: deploy.sh
        - src: disable-telemetry.yaml
          dest: disable-telemetry.yaml
        - src: post-install.yaml
          dest: post-install.yaml
      when: TESTBED is defined

    - name: disable TunedProfileName
      command: sed -i -e 's/TunedProfileName/#TunedProfileName/' /home/stack/templates-ci/{{TEST_ITEM}}/environment.yaml
      when: FIX_TUNED_AFTER_DEPLOY | bool

    - name: install script to fix tuned after overcloud deploy
      template:
        src: templates/fix_tuned_after_deploy.sh.j2
        dest: /home/stack/templates-ci/{{TEST_ITEM}}/fix_tuned_after_deploy.sh
        mode: 0755

    - name: install ansible
      yum:
        name: ansible
        state: present
      become: yes

    - name: END
      meta: end_play

    - shell: chmod u+x deploy.sh; ./deploy.sh > deploy.output
      args:
        chdir: /home/stack/templates-ci/{{TEST_ITEM}}

    - fetch:
        src: /home/stack/templates-ci/{{TEST_ITEM}}/deploy.output
        dest: deploy.output
        flat: yes

    - shell: chmod u+x fix_tuned_after_deploy.sh; ./fix_tuned_after_deploy.sh > fix_tuned.output
      args:
        chdir: /home/stack/templates-ci/{{TEST_ITEM}}

    - fetch:
        src: /home/stack/templates-ci/{{TEST_ITEM}}/fix_tuned.output
        dest: fix_tuned.output
        flat: yes

