---
- hosts: trafficgen
  gather_facts: false
  remote_user: root
  vars_files:
    - vars.yaml
  tasks:
    - name: clean up exisiting instance if any 
      shell: |
        screen -X -S trafficgen quit
        if [ -e trafficgen-ci ]; then
            rm -rf trafficgen-ci
        fi
        mkdir trafficgen-ci
    - name: copy trafficgen cmd
      template:
        src: templates/trafficgen_cmd.sh.j2 
        dest: /root/trafficgen-ci/trafficgen_cmd.sh
        mode: 0755
        owner: root
        group: root
    - shell: |
        #screen -dmS trafficgen bash -c "./trafficgen_cmd.sh" 
        ./trafficgen_cmd.sh
      args:
        chdir: /root/trafficgen-ci 

      
