---
- hosts: VMs,computes
  gather_facts: false
  tasks:
  - name: make sure all.repo exist
    copy:
      src: all.repo
      dest: /etc/yum.repos.d/all.repo
  - name: install yum-plugin-copr
    yum:
      name: yum-plugin-copr
      state: present
    register: copr
  - name: enable ndokos/pbench
    shell: yum copr enable ndokos/pbench -y
    when: copr.changed == True
  - name: install pbench-agent
    yum:
      name: pbench-agent
      state: latest

